name: '📚 Smart Doc'
description: 'Keeps your repository documented with each integration. Converts code changes into clear docs using AI.'
branding:
  icon: 'book-open'
  color: 'purple'

inputs:
  docs_folder:
    description: 'Folder where documentation is stored (default: docs)'
    required: false
    default: 'docs'
  model:
    description: 'Optional model used (default: gpt-5-mini)'
    required: false
    default: 'gpt-5-mini'
  openai_api_key:
    description: 'OpenAI API key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 📚 Smart Doc
      shell: bash
      env:
        INPUT_OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        INPUT_DOCS_FOLDER: ${{ inputs.docs_folder }}
        INPUT_MODEL: ${{ inputs.model }}
        INPUT_BRANCH: 'main'
      run: bash "${GITHUB_ACTION_PATH}/smart-doc.sh"

permissions:
  contents: write
  pull-requests: read
