name: 'Smart Doc Action'
description: 'Generate concise, diff-driven docs on every change.'
branding:
  icon: 'book-open'
  color: 'purple'

inputs:
  model:
    description: 'Optional model used (default: gpt-5-mini)'
    required: false
    default: 'gpt-5-mini'
  openai_api_key:
    description: 'OpenAI API key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install OpenAI Codex CLI
      shell: bash
      run: |
        if ! command -v codex >/dev/null 2>&1; then
          npm install -g @openai/codex
        fi
    - name: 📚 Smart Doc
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        MODEL: ${{ inputs.model }}
        GH_TOKEN: ${{ github.token }}
        GITHUB_TOKEN: ${{ github.token }}
      run: bash "${GITHUB_ACTION_PATH}/smart-doc.sh"

permissions:
  contents: write
  pull-requests: read
