name: '📚 Smart Doc'
description: 'Keeps your repository documented with each integration. Converts code changes into clear docs using AI.'
branding:
  icon: 'book-open'
  color: 'purple'

inputs:
  model:
    description: 'Optional model used (default: gpt-5-mini)'
    required: false
    default: 'gpt-5-mini'
  openai_api_key:
    description: 'OpenAI API key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 📚 Smart Doc
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        MODEL: ${{ inputs.model }}
        GH_TOKEN: ${{ github.token }}
        GITHUB_TOKEN: ${{ github.token }}

permissions:
  contents: write
  pull-requests: read
